# StatefulSet pour la base de données de cast

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.cast_bdd.nom }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.cast_bdd.label }}
  template:
    metadata:
      labels:
        app: {{ .Values.cast_bdd.label }} # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: {{ .Values.cast_bdd.statefulset.conteneur.nom }}
        image: {{ .Values.cast_bdd.statefulset.conteneur.image }}
        ports:
        - containerPort: {{ .Values.cast_bdd.statefulset.conteneur.port }}
        env:
        - name: POSTGRES_USER
          value: {{ .Values.cast_bdd.statefulset.utilisateur }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.cast_bdd.statefulset.mdp }}
        - name: POSTGRES_DB
          value: {{ .Values.cast_bdd.nom }}

---

# Service pour la base de données de cast

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.cast_bdd.nom }}
spec:
  selector:
    app: {{ .Values.cast_bdd.label }}
  type: {{ .Values.cast_bdd.service.type }}
  ports:
  - protocol: {{ .Values.cast_bdd.service.protocol }}
    port: {{ .Values.cast_bdd.service.port }}
    targetPort: {{ .Values.cast_bdd.service.targetPort }}
