# Secret pour le service movie

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cast_service.secret.nom }}
type: Opaque
stringData:
  DATABASE_URI: "postgresql://cast_db_username:cast_db_password@cast-db/{{ .Values.cast_bdd.nom }}"