# Secret pour la base de données de movie

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cast_bdd.secret.nom }}
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  POSTGRES_DB: "{{ .Values.cast_bdd.nom }}_{{ .Values.namespace }}"
#  POSTGRES_USER: "cast_db_username"
#  POSTGRES_PASSWORD: "cast_db_password"
data:
  POSTGRES_USER: {{ .Files.Get "../../dossierIdentifiantsMdp/cast-db/username.txt" | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Files.Get "../../dossierIdentifiantsMdp/cast-db/password.txt" | b64enc | quote }}
