apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-service
  template:
    metadata:
      labels:
        app: movie-service
    spec:
      containers:
      - name: movie-service
        image: "{{ .Values.movie_service.image.repository }}:{{ .Values.movie_service.image.tag }}"
        ports:
        - containerPort: 5678 # Port Conteneur Dockerfile movie-service
        env:
        - name: DATABASE_URI
          value: "postgresql://{{ .Values.database.movie.user }}:{{ .Values.database.movie.password }}@movie-db/{{ .Values.database.movie.dbName }}"
      restartPolicy: Always  # Ajoutez cette ligne pour spécifier la politique de redémarrage

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cast-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cast-service
  template:
    metadata:
      labels:
        app: cast-service
    spec:
      containers:
      - name: cast-service
        image: "{{ .Values.cast_service.image.repository }}:{{ .Values.cast_service.image.tag }}"
        ports:
        - containerPort: 1234 # Port Conteneur Dockerfile cats-service
        env:
        - name: DATABASE_URI
          value: "postgresql://{{ .Values.database.cast.user }}:{{ .Values.database.cast.password }}@cast-db/{{ .Values.database.cast.dbName }}"
      restartPolicy: Always  # Ajoutez cette ligne pour spécifier la politique de redémarrage

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-db
  template:
    metadata:
      labels:
        app: movie-db
    spec:
      containers:
      - name: movie-db
        image: postgres:12.1-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "{{ .Values.database.movie.user }}"
        - name: POSTGRES_PASSWORD
          value: "{{ .Values.database.movie.password }}"
        - name: POSTGRES_DB
          value: "{{ .Values.database.movie.dbName }}"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cast-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cast-db
  template:
    metadata:
      labels:
        app: cast-db
    spec:
      containers:
      - name: cast-db
        image: postgres:12.1-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "{{ .Values.database.cast.user }}"
        - name: POSTGRES_PASSWORD
          value: "{{ .Values.database.cast.password }}"
        - name: POSTGRES_DB
          value: "{{ .Values.database.cast.dbName }}"
---
