apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.nom }}
spec:
  ingressClassName: traefik
  rules:
    - host: {{ .Values.ingress.domaine }}
      http:
        paths:
          - path: {{ .Values.ingress.service1.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.ingress.service1.nom }}
                port:
                  number: {{ .Values.ingress.service1.nbport }}
          - path:  {{ .Values.ingress.service2.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.ingress.service2.nom }}
                port:
                  number: {{ .Values.ingress.service2.nbport }}
