# Secret pour la base de données de movie

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.movie_bdd.secret.nom }}
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.movie_bdd.nom }}
data:
  POSTGRES_USER: {{ .Files.Get "../../dossierIdentifiantsMdp/movie-db/username.txt" | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Files.Get "../../dossierIdentifiantsMdp/movie-db/password.txt" | b64enc | quote }}
