# Secret pour le service movie

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.movie_service.secret.nom }}
type: Opaque
stringData:
  CAST_SERVICE_HOST_URL: "http://{{ .Values.cast_service.nom }}:{{ .Values.cast_service.service.port }}/api/v1/casts/"
  DATABASE_URI: "postgresql://movie_db_username:movie_db_password@movie-db/{{ .Values.movie_bdd.nom }}"
