# Secret pour la base de données de movie

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.movie_bdd.secret.nom }}
type: Opaque
stringData:
  POSTGRES_USER: "movie_db_username"
  POSTGRES_PASSWORD: "movie_db_password"
  POSTGRES_DB: {{ .Values.movie_bdd.nom }}
