cast_service:
  nom: cast-service
  label: cast-service

  deployment: # Info à passer au Deployment
    conteneur: 
      nom: cast-service-conteneur
      image:
        repository: dockersebc/cast_service
        tag: ""
      port: 1234 # Port Conteneur Dockerfile cast-service
  
  service: # Info à passer au service
    type: ClusterIP
    protocol: TCP
    port: 8001 # Port à lier à l'ingress
    targetPort: 1234 # Port Conteneur Dockerfile cast-service

  secret: # Info à passer pour le secret
    nom: cast-service-secret

############################################################################

cast_bdd:
  nom: cast-db
  label: cast-db

  statefulset: # Info à passer au StatefulSet
    conteneur:
      nom: cast-bd-conteneur
      image: postgres:12.1-alpine
      port: 5432
  
  service: # Info à passer au service
    type: ClusterIP
    protocol: TCP
    port: 5432
    targetPort: 5432
  
  volume: # Info à passer pour la persistance des données
    nom: cast-db-data
    cheminMontage: /var/lib/postgresql/data
    storageClassName: local-path
    accesModes:
      - ReadWriteOnce
    storage: 1Gi

  secret: # Info à passer pour le secret
    nom: cast-db-secret

############################################################################

movie_service:
  nom: movie-service
  label: movie-service
  
  deployment: # Info à passer au Deployment
    conteneur: 
      nom: movie-service-conteneur
      image:
        repository: dockersebc/movie_service
        tag: ""
      port: 5678 # Port Conteneur Dockerfile movie-service
  
  service: # Info à passer au service
    type: ClusterIP
    protocol: TCP
    port: 8002 # Port à lier à l'ingress
    targetPort: 5678 # Port Conteneur Dockerfile movie-service

  secret: # Info à passer pour le secret
    nom: movie-service-secret

############################################################################

movie_bdd:
  nom: movie-db
  label: movie-db

  statefulset: # Info à passer au StatefulSet
    conteneur:
      nom: movie-db-conteneur
      image: postgres:12.1-alpine
      port: 5432

  service: # Info à passer au service
    type: ClusterIP
    protocol: TCP
    port: 5432
    targetPort: 5432
  
  volume: # Info à passer pour la persistance des données
    nom: movie-db-data
    cheminMontage: /var/lib/postgresql/data
    storageClassName: local-path
    accesModes:
      - ReadWriteOnce
    storage: 1Gi
  
  secret: # Info à passer pour le secret
    nom: movie-db-secret

############################################################################

ingress: # Info à passer à l'Ingress
  nom: examjenkins-ingress
  domaine: "dev.exam-jenkins.seb-coasne.cloudns.biz"

  service1:
    path: /api/v1/casts
    nom: cast-service
    nbport : 8001 # Port Service cast_service

  service2:
    path: /api/v1/movies
    nom: movie-service 
    nbport : 8002 # Port Service movie_service
